"""
Audio Manager for 2048.
Automatically downloads sound effects on first run and handles playback.
"""
import os
import urllib.request
import urllib.error
import pygame as pg
#pylint: disable=E1101

# @generated "all" gemini -3 pro - this entire file was generated by AI - while i picked the sounds

# Direct links to CC0 licensed sounds from GitHub
ASSET_URLS = {
    # move sound - subtle click from rse/soundfx (CC0/CC-BY-3.0)
    'move.wav': 'https://raw.githubusercontent.com/rse/soundfx/master/soundfx.d/click1.mp3',

    # merge sound - positive bling from rse/soundfx (CC0/CC-BY-3.0)
    'merge.wav': 'https://raw.githubusercontent.com/rse/soundfx/master/soundfx.d/bling1.mp3',

    # win sound - triumph fanfare from rse/soundfx (CC0/CC-BY-3.0)
    'win.wav': 'https://raw.githubusercontent.com/rse/soundfx/master/soundfx.d/triumph1.mp3',

    # lose sound - alarm/error from rse/soundfx (CC0/CC-BY-3.0)
    'lose.wav': 'https://raw.githubusercontent.com/rse/soundfx/master/soundfx.d/alarm2.mp3',
}

_sounds = {}

def initialize():
    """
    Called by main.py. Checks for assets, downloads them if missing,
    and initializes the mixer.
    """
    # define where assets should live
    base_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'assets')

    # check and Download assets
    _ensure_assets_exist(base_path)

    # initialize Pygame Mixer
    try:
        pg.mixer.init(frequency=44100, size=-16, channels=2, buffer=2048)
        _load_sounds(base_path)
        print(" Audio system initialized.")
    except pg.error as e:
        print(f"Warning: Audio system failed to initialize. {e}")

def _ensure_assets_exist(base_path):
    """Checks if files exist, downloads them if not."""
    if not os.path.exists(base_path):
        os.makedirs(base_path)
        print(f" Created assets directory at {base_path}")

    print("\n" + "="*60)
    print("AUDIO SETUP - Checking sound effects...")
    print("="*60)

    missing_files = []
    for filename in ASSET_URLS:
        file_path = os.path.join(base_path, filename)
        if not os.path.exists(file_path):
            missing_files.append(filename)

    if missing_files:
        print(f"\nMissing {len(missing_files)} sound file(s).")
        print("These are free, CC0/CC-BY licensed sounds from SoundFX collection.")
        choice = input("\nDownload sound effects? [Y/n]: ").strip().lower()

        if choice not in ['', 'y', 'yes']:
            print("Starting game without sound effects...")
            return

        print("\n Downloading sound effects...")
        for filename, url in ASSET_URLS.items():
            file_path = os.path.join(base_path, filename)

            if not os.path.exists(file_path):
                print(f"   Downloading {filename}...")
                try:
                    req = urllib.request.Request(url, headers={
                        'User-Agent': 'Mozilla/5.0'
                    })
                    with urllib.request.urlopen(req, timeout=15) as response:
                        with open(file_path, 'wb') as f:
                            f.write(response.read())
                    print(f"   ✓ {filename} downloaded!")
                except (urllib.error.URLError, OSError, IOError) as e:
                    print(f"      FAILED to download {filename}")
                    print(f"      Error: {e}")

        print("\n" + "="*60)
        print(" Download complete!")
        print("="*60)
        print("\n Tip: Delete 'assets/' folder to re-download.\n")
    else:
        print("All sound effects present!")

def _load_sounds(base_path):
    """Load the downloaded files into memory."""
    # @generated "all" gemini -3 pro - this entire function was generated by AI
    # load sound effects
    for name in ['move', 'merge', 'win', 'lose']:
        filename = f"{name}.wav"
        full_path = os.path.join(base_path, filename)

        if os.path.exists(full_path):
            try:
                _sounds[name] = pg.mixer.Sound(full_path)
                _sounds[name].set_volume(0.5)  # set volume to 50%
            except pg.error as e:
                print(f"Could not load sound {filename}: {e}")

def play_sound(name):
    """Play a sound effect by name."""
    if name in _sounds:
        try:
            _sounds[name].play()
        except pg.error:
            pass
